[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://coral-thankful-moonstone.glitch.me/api/:splat"
  status = 200

#"https://coral-thankful-moonstone.glitch.me/api/:splat"
  
  
#"https://ebiwoni-api.netlify.app/api/:splat"