[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "https://cashpanthers-b15ff30073b4.herokuapp.com/api/:splat"
#to = "https://pandapulse.netlify.app/api/:splat"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
