
export const ALL_WORKERS_REQUEST = 'ALL_WORKERS_REQUEST'
export const ALL_WORKERS_SUCCESS = 'ALL_WORKERS_SUCCESS'
export const ALL_WORKERS_FAIL = 'ALL_WORKERS_FAIL'
export const WORKER_DETAILS_REQUEST = 'WORKER_DETAILS_REQUEST'
export const WORKER_DETAILS_SUCCESS = 'WORKER_DETAILS_SUCCESS'
export const WORKER_DETAILS_FAIL = 'WORKER_DETAILS_FAIL'
export const CREATE_WORKER_REQUEST = 'CREATE_WORKER_REQUEST'
export const CREATE_WORKER_SUCCESS = 'CREATE_WORKER_SUCCESS'
export const CREATE_WORKER_FAIL = 'CREATE_WORKER_FAIL'
export const CREATE_WORKER_RESET = 'CREATE_WORKER_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
